In [1]:
!pip install --upgrade tensorflow==1.15

You should consider upgrading via the '/root/venv/bin/python -m pip install --upgrade pip' command.


## **IMPORT LIBRARY**

In [2]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split

## **IMPORT DATASET**

In [3]:
df = pd.read_csv("classification.csv")
df.head(10)

class cap-shape cap-surface  cap-color  bruises odor stalk-shape  \
0     p         x           s          4        1    p           e   
1     e         x           s          9        1    a           e   
2     e         b           s          8        1    l           e   
3     p         x           y          8        1    p           e   
4     e         x           s          3        0    n           t   
5     e         x           y          9        1    a           e   
6     e         b           s          8        1    a           e   
7     e         b           y          8        1    l           e   
8     p         x           y          8        1    p           e   
9     e         b           s          9        1    a           e   

   stalk-root  stalk-surface-above-ring  stalk-surface-below-ring  \
0           3                         2                         2   
1           2                         2                         2   
2           2                         2                         2   
3           3                         2                         2   
4           3                         2                         2   
5           2                         2                         2   
6           2                         2                         2   
7           2                         2                         2   
8           3                         2                         2   
9           2                         2                         2   

   stalk-color-above-ring  stalk-color-below-ring veil-type  veil-color  \
0                       7                       7         p           2   
1                       7                       7         p           2   
2                       7                       7         p           2   
3                       7                       7         p           2   
4                       7                       7         p           2   
5                       7                       7         p           2   
6                       7                       7         p           2   
7                       7                       7         p           2   
8                       7                       7         p           2   
9                       7                       7         p           2   

   ring-number  ring-type  spore-print-color population habitat  
0            1          4                  2          s       u  
1            1          4                  3          n       g  
2            1          4                  3          n       m  
3            1          4                  2          s       u  
4            1          0                  3          a       g  
5            1          4                  2          n       g  
6            1          4                  2          n       m  
7            1          4                  3          s       m  
8            1          4                  2          v       g  
9            1          4                  2          s       m

## **FEATURE SELECTION**

In [4]:
for index, i in enumerate(df['cap-shape']):
    if (i == "b"):
        df['cap-shape'][index] = 1
    elif (i == "c"):
        df['cap-shape'][index] = 2
    elif (i == "x"):
        df['cap-shape'][index] = 3
    elif (i == "f"):
        df['cap-shape'][index] = 4
    elif (i == "k"):
        df['cap-shape'][index] = 5
    elif (i == "s"):
        df['cap-shape'][index] = 6

/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/inde

In [5]:
for index, i in enumerate(df['odor']):
    if (i == "a"):
        df['odor'][index] = 1
    elif (i == "l"):
        df['odor'][index] = 2
    elif (i == "c"):
        df['odor'][index] = 3
    elif (i == "y"):
        df['odor'][index] = 4
    elif (i == "f"):
        df['odor'][index] = 5
    elif (i == "m"):
        df['odor'][index] = 6
    elif (i == "n"):
        df['odor'][index] = 7
    elif (i == "p"):
        df['odor'][index] = 8
    elif (i == "s"):
        df['odor'][index] = 9

/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ret

In [6]:
for index, i in enumerate(df['habitat']):
    if (i == "g"):
        df['habitat'][index] = 1
    elif (i == "l"):
        df['habitat'][index] = 2
    elif (i == "m"):
        df['habitat'][index] = 3
    elif (i == "p"):
        df['habitat'][index] = 4
    elif (i == "u"):
        df['habitat'][index] = 5
    elif (i == "w"):
        df['habitat'][index] = 6
    elif (i == "d"):
        df['habitat'][index] = 7

/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.

In [7]:
dataset = df[['class', 'cap-shape', 'cap-color', 'odor', 'stalk-color-above-ring', 'stalk-color-below-ring', 'veil-color', 'ring-number', 'habitat']]
dataset.head()

class cap-shape  cap-color odor  stalk-color-above-ring  \
0     p         3          4    8                       7   
1     e         3          9    1                       7   
2     e         1          8    2                       7   
3     p         3          8    8                       7   
4     e         3          3    7                       7   

   stalk-color-below-ring  veil-color  ring-number habitat  
0                       7           2            1       5  
1                       7           2            1       1  
2                       7           2            1       3  
3                       7           2            1       5  
4                       7           2            1       1

In [8]:
# Mengecek null value, jika ada maka akan diisi menggunakan fillna

dataset = dataset.fillna(dataset.mean())
dataset.isnull().sum()

class                     0
cap-shape                 0
cap-color                 0
odor                      0
stalk-color-above-ring    0
stalk-color-below-ring    0
veil-color                0
ring-number               0
habitat                   0
dtype: int64

In [9]:
dataset.isnull().values.sum()

0

## **DEFINE FEATURES**

In [10]:
x = dataset.drop(['class'], axis = 1)
y = dataset['class'].values.reshape(-1, 1)

## **FEATURE SELECTION USING PCA**

In [11]:
from sklearn.decomposition import PCA

In [12]:
def normalize_dataset(dataset,mean):
  return dataset - mean

In [13]:
def calculate_mean(dataset):
    return tf.reduce_mean(dataset, axis=0)

In [14]:
def apply_pca(normalize_dataset):
    pca = PCA(n_components = 4)
    pca = pca.fit(normalize_dataset)
    return pca.transform(normalize_dataset)

In [15]:
dx = x.to_numpy()
dx.shape

(8124, 8)

In [16]:
mean = calculate_mean(dx)
dx = normalize_dataset(dx, mean)

In [17]:
with tf.Session() as sess:
    dx = sess.run(dx)
    result = apply_pca(dx)
    print(result)

[[-1.12187816 -1.69086742 -0.81999425 -1.88364993]
 [ 7.05826793  1.03318879 -1.43961859  1.88020186]
 [ 5.01336195  1.19414658 -2.31075667  1.35858275]
 ...
 [ 0.28078336 -0.7782554   2.72402775 -0.26989508]
 [ 1.9035913  -1.94177923 -0.12803779  1.79110369]
 [ 0.37347162 -0.7404559   2.6807996  -0.22899736]]


## SPLIT DATASET

In [18]:
# Split dataset:

n_train = int(len(dataset) * 0.7)
n_test = int(len(dataset) * 0.2)
# train_dataset = dataset[:n_train] # train
# test_dataset = dataset[n_train:(n_train + n_test)] # test/validation
# eval_dataset = dataset[n_test:] # evaluation

In [19]:
x_train = result[:n_train, :] 
y_train = dataset.iloc[:n_train, 0].values.reshape(-1, 1)
x_test = result[n_train:(n_train + n_test)]
y_test = dataset.iloc[n_train:(n_train + n_test), 0].values.reshape(-1, 1)
x_val = result[n_test:]
y_val = dataset.iloc[n_test:, 0].values.reshape(-1, 1)

In [20]:
encoder = OneHotEncoder().fit(y_train)
y_train = encoder.transform(y_train).toarray()
y_test = encoder.transform(y_test).toarray()
y_val = encoder.transform(y_val).toarray()

In [21]:
y_train.shape

(5686, 2)

## **TRAINING**

In [22]:
# Normalization using StandardScaler:

scaler = StandardScaler().fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
x_val = scaler.transform(x_val)

In [23]:
# Variable Pembantu:
epoch = 2500
learning_rate = 0.0001

In [24]:
x_train, x_test, x_val = x_train.astype('float32'), x_test.astype('float32'), x_val.astype('float32')
y_train, y_test, y_val = y_train.astype('float32'), y_test.astype('float32'), y_val.astype('float32')

In [25]:
# layer = {
#     'input': 4,
#     'hidden': 3,
#     'output': 1
# }

In [26]:
n_features = x_train.shape[1]
n_classes = y_train.shape[1]
neurons = [n_features, 6, n_classes]
n_layers = len(neurons)

In [27]:
parameters = {
    'W1' : tf.Variable(
        tf.random.normal([
            n_features, neurons[0]
        ]),
        tf.float32
    ),
    'B1' : tf.Variable(
        tf.random.normal([1,  neurons[0]]),
        tf.float32
    ),
    'W2' : tf.Variable(
        tf.random.normal([
            neurons[0], neurons[1]
        ]),
        tf.float32
    ),
    'B2' : tf.Variable(
        tf.random.normal([1,  neurons[1]]),
        tf.float32
    ),
    'W3' : tf.Variable(
        tf.random.normal([
            neurons[1], neurons[2]
        ]),
        tf.float32
    ),
    'B3' : tf.Variable(
        tf.random.normal([1,  neurons[2]]),
        tf.float32
    )
}

In [28]:
def forward_pass(x):
  z1 = tf.matmul(x, parameters['W1']) + parameters['B1']
  a1 = tf.nn.sigmoid(z1)

  z2 = tf.matmul(a1, parameters['W2']) + parameters['B2']
  a2 = tf.nn.sigmoid(z2)

  z3 = tf.matmul(a2, parameters['W3']) + parameters['B3']
  a3 = tf.nn.sigmoid(z3)

  return a3

In [29]:
# Tensor Placeholder:
input_feature = tf.placeholder(tf.float32, name = 'feature')
input_target = tf.placeholder(tf.float32, name = 'target')

In [30]:
y = forward_pass(input_feature)
# MSE Calculation
loss = tf.reduce_mean(0.5 * (input_target - y) ** 2)
train = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)
saver = tf.train.Saver()

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [31]:
true_pred = tf.equal(tf.argmax(y, axis=1), tf.argmax(input_target, axis=1))
acc = tf.reduce_mean(tf.cast(true_pred, tf.float32))

In [32]:
num_epoch = 2500

In [ ]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    train_dict = {
        input_feature: x_train,
        input_target: y_train
    }

    test_dict = {
        input_feature: x_test,
        input_target: y_test
    }

    best_loss = float('inf')

    for epoch in range(num_epoch):
        # Update weight and bias, training the network:
        sess.run(train, feed_dict = train_dict)

        if epoch % 25 == 0:
            print(f'Epoch {epoch}\t| Loss: {sess.run(loss, feed_dict = train_dict)}')
        elif epoch == 125: 
            # After reaching the 125th epoch, calculate validation error
            val_loss = sess.run(loss, feed_dict = test_dict)
            # Record the validation error and save the model to file
            saver.save(sess, '/.best_model.ckpt')

        elif epoch % 125 == 0:
            if val_loss < best_loss:
                best_loss = val_loss
                saver.save(sess, '/.best_model.ckpt')
    
    saver.save(sess, './bpnn-model.ckpt')

Epoch 0	| Loss: 0.2070842981338501
Epoch 25	| Loss: 0.2070780247449875
Epoch 50	| Loss: 0.20707152783870697
Epoch 75	| Loss: 0.20706523954868317
Epoch 100	| Loss: 0.20705898106098175
Epoch 125	| Loss: 0.207052543759346
Epoch 150	| Loss: 0.2070462554693222
Epoch 175	| Loss: 0.20704005658626556
Epoch 200	| Loss: 0.2070336937904358
Epoch 225	| Loss: 0.2070273458957672
Epoch 250	| Loss: 0.20702093839645386
Epoch 275	| Loss: 0.20701444149017334
Epoch 300	| Loss: 0.2070080190896988
Epoch 325	| Loss: 0.20700183510780334
Epoch 350	| Loss: 0.20699544250965118
Epoch 375	| Loss: 0.20698904991149902
Epoch 400	| Loss: 0.2069825828075409
Epoch 425	| Loss: 0.2069765031337738
Epoch 450	| Loss: 0.20696993172168732
Epoch 475	| Loss: 0.206963449716568
Epoch 500	| Loss: 0.206957146525383
Epoch 525	| Loss: 0.20695097744464874
Epoch 550	| Loss: 0.20694459974765778
Epoch 575	| Loss: 0.20693807303905487


## EVALUATION

In [ ]:
with tf.Session() as sess:
    saver.restore(sess, './bpnn-model.ckpt')

    val_dict = {
        input_feature: x_val,
        input_target: y_val
    }

    eval_acc = sess.run(acc, feed_dict = val_dict)
    print(sess.run(loss, feed_dict = val_dict))
    print(f"Evaluation Accuracy: {eval_acc * 100}%")

INFO:tensorflow:Restoring parameters from ./bpnn-model.ckpt
0.15647647
Evaluation Accuracy: 57.27692246437073%


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=55039d84-69f2-422d-ba2a-a931d944300b' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>